### PR TITLE
Fix healing interrupted and medkit given to player on new match

### LINKED ISSUE #399: Medkits bugging
Use medkit before round ends. End the round before you finished healing. Healing is interrupted when you spawn in new map and you get a medikit. Yay.

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #399

### CODE REVIEW

File: mods/pvp/medkits/init.lua [hunk 1]
```diff
@@ -62,6 +62,16 @@ local function stop_healing(player, interrupted)
 	player:hud_remove(info.hud)
 end
 
+ctf_flag.register_on_precapture(function()
+		for name, info in pairs(players) do
+			players[name]=nil
+			local player=minetest.get_player_by_name(name)
```
Comment (ClobberXD) [inline mods/pvp/medkits/init.lua]:
```suggestion
			local player = minetest.get_player_by_name(name)
```

**Comment by appgurueu** [comment]
nice
