### PR TITLE
Fix server crash when vote kicking an already left player

### LINKED ISSUE #405: Crash due to missing player check before a vote-kick

### PR DESCRIPTION
**Pull request by Thomas--S**
Also fixes the /unblock command which didn't work previously

Tested and seems to work.

Fixes #405

### CODE REVIEW

**Comment by Thomas--S** [comment]
@ClobberXD PR updated according to your suggestions. Tested and seems to work. Thanks for your review.

File: mods/other/vote/vote_kick.lua [hunk 1]
```diff
@@ -37,6 +37,15 @@ minetest.register_chatcommand("vote_kick", {
 
 		minetest.log("warning", "Player '" .. name .. "' started a vote" ..
 							" to kick '" .. param .. "'")
+
+
+		if not vlist[param] then
+			vlist[param] = {
+				ip = minetest.get_player_ip(param),
+				locked = false
```
Comment (ClobberXD) [inline mods/other/vote/vote_kick.lua]: Is `locked` now required? To check if the player's kick vote is still active, you could do

```lua
if vlist[name] and minetest.get_player_by_name(name) then
    -- Player is a target of a kick vote, and the vote still hasn't ended (because the player is still in-game).
end
```

Or, you could define `vlist[name]` after the player has been kicked.

Comment (Thomas--S) [reply mods/other/vote/vote_kick.lua]: I think that the current situation is more obvious and extendable.
The IP address can also be stored in a more understandable way with the current approach.

So, I'd prefer not to change it.

Comment (ClobberXD) [reply mods/other/vote/vote_kick.lua]: Alright, that's fine by me. :+1:

**Comment by Thomas--S** [comment]
**UPDATE:** Added a second commit to fix a server crash on priv grant.
