### PR TITLE
Fix team-chest shift-click

### LINKED ISSUE #129: Shift-clicking items from/into team-chests doesn't work
Probably due to the modified formspec of the team-chest with respect to the default chest.

### PR DESCRIPTION
**Pull request by shivajiva101**
modified to add the correct inventory refs to the listring
fixes #129

### CODE REVIEW

**Comment by ClobberXD** [comment]
Thanks for the PR.

I tested, and it seems like shift-clicking is only possible between player's `main` list and the team-chest's `main` list. Please also include the `pro` list in the listring in such a way that allows players to directly shift-click items from `pro` to their `main` inv.

The issue here is that since there are three lists in the listring, the shift-clicked item will have to pass through the chest's `main` list while either moving to the `pro` list, or from the `pro` list.

**Comment by ClobberXD** [comment]
To address the above issue, here's what can be done:

- If player isn't "pro", add player's `main` and chest's `main` to listring.
- Else add player's `main` and chest's `pro` to listring.
  - When shift-clicking into the `pro` list, check if list is full, and automatically transfer the item to the chest's `main` list.

**Comment by shivajiva101** [comment]
In my tests normal player can shift click in and out of the chest main inventory, pro players can shift-click in and out of the pro inventory, shift click out of chest main and transfer between pro and main manually.
I already attended to normal players not having pro added to the listring, it's pretty ugly shift clicking round player inv > chest main > chest pro > player inv as you suggest.

**Comment by ClobberXD** [comment]
In my testing, even pros can only shift-click to the main section. But pros can shift-click **from** the pro-section. I'd like to be able to shift-click **only** to and from the pro-section, with the overflow automatically being transferred to the main section.

File: mods/ctf_team_base/chest.lua [hunk 1]
```diff
@@ -90,15 +90,16 @@ for _, chest_color in pairs(colors) do
...
 			else
-				formspec = formspec .. "listring[current_name;pro]" ..
+				formspec = formspec ..
 					"label[5,-0.2;" .. minetest.formspec_escape("You need 1k+ score and 1.5+ KD") .. "]"
 			end
 
 			formspec = formspec ..
-				"listring[current_name;main]" ..
+				"listring[" .. chestinv ..";main]" ..
 				"listring[current_player;main]" ..
```
Comment (ClobberXD) [inline mods/ctf_team_base/chest.lua]: Note that `listring[current_player;main]` is being added twice for pros. Maybe move all listring elements inside the if-else blocks?

Comment (shivajiva101) [reply mods/ctf_team_base/chest.lua]: listring is added twice so pro goes back to player inventory instead of chest main

Comment (ClobberXD) [reply mods/ctf_team_base/chest.lua]: > listring player main is added twice so pro goes back to player inventory instead of chest main

Ah, I see... Makes sense.

> I'm happy to close this so you can do it your way now I have shown what was preventing shift-click

You've already opened a PR, and you can continue this by all means. I'm just voicing my thoughts... :)

**Comment by ClobberXD** [comment]
Tested by only adding pro-section and player's `main` list to listring for pros. One obvious issue is that pros would not be able to shift-click items from the main section. I also experimented with overflow from pro-section to main-section if pro-section is full, and the results are promising.

**Comment by shivajiva101** [comment]
how are you handling the overflow?

**Comment by ClobberXD** [comment]
```lua
if listname ~= "pro" or get_is_player_pro(pstat) then
	local chestinv = minetest.get_inventory({
		type = "node",
		pos = {x = pos.x, y = pos.y, z = pos.z}
	})
	if chestinv:room_for_item("pro", stack) then
		return stack:get_count()
	else
		-- Not enough room
		local balance = chestinv:add_item("pro", stack)
		local balance_2 = chestinv:add_item("main", balance)
		-- Still need to somehow replace the original stack with balance_2
		return 0
	end
else
	return 0
end
```

**Comment by shivajiva101** [comment]
I think chest main needs checking it can accommodate balance_2 and if not return it to player main to encompass the possibilities of overflow

**Comment by ClobberXD** [comment]
> I think chest main needs checking it can accommodate balance_2 and if not return it to player main to encompass the possibilities of overflow

`balance` is the leftover from the original stack that can't be accomodated in `pro`. `balance_2` is the leftover of balance which in very rare cases can't be completely added to `main`, in which case `balance_2` will replace the original stack in the player's inv. What's left to do, is to figure out how the original stack can be accessed...

**Comment by shivajiva101** [comment]
Ah yes my bad, balance_2 is the overflow from chest main

**Comment by shivajiva101** [comment]
Guess you mean like this...
```lua
if listname ~= "pro" or get_is_player_pro(pstat) then
	minetest.chat_send_all(listname)
	local chestinv = minetest.get_inventory({
		type = "node",
		pos = {x = pos.x, y = pos.y, z = pos.z}
		})
	local playerinv = player:get_inventory()
	if chestinv:room_for_item("pro", stack) then
		return stack:get_count()
	else
		-- Not enough room, handle everything
		local leftovers = chestinv:add_item("pro", stack)
		local leftover = chestinv:add_item("main", leftovers)
		local n_stack = stack
		n_stack:set_count(stack:get_count() - leftover:get_count())
		playerinv:remove_item("main", n_stack)
		return 0
	end
else
	return 0
end
```

**Comment by shivajiva101** [comment]
As a pro player you have access to 2 lists in the chest plus your inventory giving us a 3 list ring, dropping chest main from the ring means no shift-click for pro players from that list, including it means shift clicks in pro go to chest main before player inventory. I can alter the sequence to go one way round or the other, after all it's a listring but your requirements break the listring concept somewhat

**Comment by ClobberXD** [comment]
Haven't tested, but the code looks good.

> As a pro player you have access to 2 lists in the chest plus your inventory giving us a 3 list ring, dropping chest main from the ring means no shift-click for pro players from that list, including it means shift clicks in pro go to chest main before player inventory. I can alter the sequence to go one way round or the other, after all it's a listring but your requirements break the listring concept somewhat

I agree... With `main` list in the listring, the item has to go through it either when putting into `pro` or taking from `pro`. It's just very confusing for the players if the item goes via `main`, when they shift-click from/to the `pro` section. But on the other hand, pros always prefer putting things into and taking things from the pro section, and hardly every use the main section. Adding only the pro section to the listring **and** handling the overflow seems to be a relatively better solution than the others.

**Comment by shivajiva101** [comment]
> Haven't tested, but the code looks good.

It works, I tested it.

> Adding only the pro section to the listring and handling the overflow seems to be a relatively better solution than the others.

okay sounds like a plan!

**Comment by shivajiva101** [comment]
Should be exactly what you wanted before you decided to compromise, please test

File: mods/ctf_team_base/chest.lua [hunk 2]
```diff
@@ -118,7 +120,23 @@ for _, chest_color in pairs(colors) do
 			end
 
 			if (from_list ~= "pro" and to_list ~= "pro") or get_is_player_pro(pstat) then
-				return count
+				if to_list == "helper" then
+					-- handle move & overflow
+					local chestinv = minetest.get_inventory({
+						type = "node",
+						pos = {x = pos.x, y = pos.y, z = pos.z}
```
Comment (rubenwardy) [inline mods/ctf_team_base/chest.lua]: No need to copy the position like this, it can be passed straight in

Comment (shivajiva101) [reply mods/ctf_team_base/chest.lua]: yea I was just reflecting the code style I found in the file, not sure how to block hidden though, could you show me what you mean

Comment (shivajiva101) [reply mods/ctf_team_base/chest.lua]: That would box it in nicely I believe

**Comment by shivajiva101** [comment]
Seems like I was only reflecting ClobberXDs code style, fixed

File: mods/ctf_team_base/chest.lua [hunk 3]
```diff
@@ -118,7 +120,20 @@ for _, chest_color in pairs(colors) do
 			end
 
 			if (from_list ~= "pro" and to_list ~= "pro") or get_is_player_pro(pstat) then
-				return count
+				if to_list == "helper" and from_list ~= "main" then
```
Comment (rubenwardy) [inline mods/ctf_team_base/chest.lua]: remove from_list ~= main

File: mods/ctf_team_base/chest.lua [hunk 4]
```diff
@@ -118,7 +120,20 @@ for _, chest_color in pairs(colors) do
...
+					n_stack:set_count(stack:get_count() - leftover:get_count())
+					chestinv:remove_item("helper", stack)
+					chestinv:remove_item("pro", n_stack)
+					return 0
+				else
+					return count
+				end
 			else
 				return 0
 			end
```
Comment (rubenwardy) [inline mods/ctf_team_base/chest.lua]: add

```lua
if to_list == "helper" then
return 0
end
```

**Comment by rubenwardy** [comment]
> not sure how to block hidden though,

* Add check to top of allow put and allow take:

  ```lua
  if to_list == "helper" then
    return 0
  end
  ```

* Add check after pro section stuff, similar form

Check that `return 0` stops the move in all these cases

File: mods/ctf_team_base/chest.lua (hunk 4 above)
Comment (shivajiva101) [reply mods/ctf_team_base/chest.lua]: isn't that covered by the scope of
```lua
if to_list == "helper" then
	-- handle move to player inventory
	local chestinv = minetest.get_inventory({type = "node", pos = pos})
	local playerinv = player:get_inventory()
	local stack = chestinv:get_stack(from_list, from_index)
	local leftover = playerinv:add_item("main", stack)
	local n_stack = stack
	n_stack:set_count(stack:get_count() - leftover:get_count())
	chestinv:remove_item("helper", stack)
	chestinv:remove_item("pro", n_stack)
	return 0
else
	return count
end
'''

Comment (shivajiva101) [reply mods/ctf_team_base/chest.lua]: Ah outside of the conditional we have the possibility of it passing through if from_list is helper and  to_list is not pro! Okay got it :+1:

Comment (shivajiva101) [reply mods/ctf_team_base/chest.lua]: Wouldn't it be better to check the from_list isn't helper?
